version: '2'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: railsdb
    ports:
      - "23306:3306"
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d
  redis:
    image: redis:3.2.6
    ports:
      - "26379:6379"